// "use client"
import "@uploadthing/react/styles.css"
import ResponsiveAppBar from "../components/appbar"
import LabelBottomNavigation from "../components/bottomnav";
import Footer from "../components/footer"
// import UserIcon from "./components/userIcon"
import { cookies } from "next/headers";
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import PermIdentityIcon from '@mui/icons-material/PermIdentity';
import IconButton from '@mui/material/IconButton';
// import { useRouter } from 'next/navigation';
import { ProductCardsSkeleton } from '@components/skeletons'
// import { WishlistProvider } from "@app/context/WishlistContext";
// import { AppProps } from "next/app";

import 'styles/global.css'
// import ClientComponent from "@components/cookieClient";
export const metadata = {
  name: "viewport",
  content: "initial-scale=1, width=device-width, height=300",
  title: "NFC Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ Component, pageProps, children }) {
  // const isLoggedIn = <ClientComponent/>
  const isLoggedIn = cookies().get("Authorization");
  return (
    // <WishlistProvider>
    <html lang="en">
      <body>
        <ResponsiveAppBar >
          {/* <div>
            {
              !isLoggedIn ?
                <IconButton aria-label='account' href="/userlogin">
                  <PermIdentityIcon />
                </IconButton>
                :
                <IconButton aria-label='profile' href="/profile">
                  <AccountCircleIcon />
                </IconButton>
            }
          </div> */}
        </ResponsiveAppBar>
        {/* <Component {...pageProps} /> */}
        {children}
        <Footer />
        {/* <LabelBottomNavigation /> */}
      </body>
    </html>
    // </WishlistProvider>
  );
}
