import * as React from 'react';
import "@uploadthing/react/styles.css"
import ResponsiveAppBar from "../components/appbar"
import LabelBottomNavigation from "../components/bottomnav";
import Footer from "../components/footer"
// import UserIcon from "./components/userIcon"
import { cookies } from "next/headers";
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import PermIdentityIcon from '@mui/icons-material/PermIdentity';
import IconButton from '@mui/material/IconButton';
import 'styles/global.css'
export const metadata = {
  name: "viewport",
  content: "initial-scale=1, width=device-width, height=300",
  title: "NFC Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isLoggedIn = cookies().get("Authorization");
  return (
    <html lang="en">
      <body>
        <React.Suspense>
          <ResponsiveAppBar >
            <div>
              {
                !isLoggedIn ?
                  <IconButton aria-label='account' href="/login">
                    <PermIdentityIcon />
                  </IconButton>
                  :
                  <IconButton aria-label='profile' href="/profile">
                    <AccountCircleIcon />
                  </IconButton>
              }
            </div>
          </ResponsiveAppBar>
        </React.Suspense>
        {children}
        <Footer />
        <LabelBottomNavigation />
      </body>
    </html>
  );
}
